name: install ssh and deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Run command over ssh
        run: ssh -p 2210 root@185.241.10.173 "df -h"
        
        
    
