name: install ssh and deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
        
      - name: add key to known_hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT}} -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts
      - name: Run command over ssh
        run: ssh -p 2210 root@185.241.10.173 "df -h"
        
        
    
